codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 85%
        threshold: 2%
        base: auto
    patch:
      default:
        target: 80%
        threshold: 2%

comment:
  layout: "header,diff,flags,files,footer"
  behavior: default
  require_changes: false