project:
  type: website
  output-dir: _site

website:
  title: "Setwise"
  description: "Professional LaTeX Quiz Generator"
  site-url: "https://nipunbatra.github.io/setwise"
  repo-url: "https://github.com/nipunbatra/setwise"
  
  navbar:
    background: light
    foreground: dark
    title: "🎯 Setwise"
    left:
      - href: index.qmd
        text: Home
      - href: quickstart.qmd
        text: Quick Start
      - href: features.qmd
        text: Features
      - href: examples.qmd
        text: Examples
      - href: installation.qmd
        text: Install
    right:
      - icon: github
        href: https://github.com/nipunbatra/setwise
        aria-label: GitHub
        
  page-footer:
    center: "© 2024 Setwise - MIT License"

format:
  html:
    theme: 
      light: [cosmo, custom.scss]
    css: styles.css
    toc: true
    toc-location: right
    code-copy: true
    code-fold: false
    smooth-scroll: true
    
execute:
  freeze: auto