"""
Quiz Questions
Generated by Setwise
"""

mcq = [{'question': 'What is the capital of France?', 'options': ['London', 'Berlin', 'Paris', 'Madrid'], 'answer': 'Paris', 'marks': 1}, {'question': 'Calculate: $2^3 + 5 \\times 2$', 'options': ['16', '18', '20', '22'], 'answer': '18', 'marks': 2}]

subjective = [{'question': "Explain Newton's first law of motion.", 'answer': 'An object at rest stays at rest and an object in motion stays in motion with the same speed and in the same direction unless acted upon by an unbalanced force.', 'marks': 5}, {'question': 'Derive the quadratic formula from $ax^2 + bx + c = 0$.', 'answer': 'Starting with $ax^2 + bx + c = 0$, divide by $a$: $x^2 + \\frac{b}{a}x + \\frac{c}{a} = 0$. Complete the square to get $x = \\frac{-b \\pm \\sqrt{b^2-4ac}}{2a}$.', 'marks': 8}]
